### ISSUE TITLE
Questions to update for v2

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [OpenIntroStat/ims#105]
- Deprecate:
  - Partners' ages and heights (old data)

**Comment by hardin47** [comment]
The residual exercises are mostly in chapter 7.  That isn't super problematic, but a lot of the narrative got moved to 24 so that we could talk about how the violation of conditions would actually affect the inference aspects.  For V2 we need more LINE problems in 24, and we also need to ask questions (add guided practice, too?) about what the consequences for LINE violations are.
