### ISSUE TITLE
p. 191 Footnote 6 different price

### ISSUE THREAD

**Issue by IZE85** [OpenIntroStat/ims#189]
If I follow the formula on page 191 in Footnote 6 I get a different price than you: Mine is (rounded) $381,427.

Could this be a consequence of the different way "coolingother" is coded compared to "cooling"?

**Comment by hardin47** [comment]
revisit after issue #188

**Comment by hardin47** [comment]
we have a rounding issue here.   the predicted value that comes directly out of the model using `predict()` is 298,152.28.  when you use the rounded coefficients, you get 297,570.   seems like a good amount to be off by, but i don't know that it is worth adding all the sig figs.  

here are some options for solutions:

1. leave it with the discrepancy
2. add decimals to the footnote but not table 10.4 (the lm output)
3. add decimals to the footnote and table 10.4
4. leave the discrepancy but add “up to rounding error”
5. change the predicted value to be hard coded instead of from predict()

**Comment by hardin47** [comment]
and whatever we do will also impact the follow question (which is about the residual)

**Comment by hardin47** [comment]
ok.  went with #5 (but i left the R code in the .Rmd file with a note that we didn't use the R code).  fixed both the prediction GP as well as the residual GP.
