### ISSUE TITLE
Define density plot

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [OpenIntroStat/ims#219]
From Jeff Witmer:

I don't think I had ever heard of a ridge plot before reading page 70, but you mention density plots there, yet I don't think you introduce density plots earlier. I was expecting to see density plot in bold and some definition of what a density plot is.

**Comment by hardin47** [comment]
in section 4.6 we describe faceting and what not.  but it isn't until chapter 5 that histograms, box plots, and densities are introduced.  instead of trying to introduce histograms, box plots, and densities in chapter 4 (or reorganize everything), I added a pointer from chapter 4 to chapter 5:  e.g., "(see Section 5.5 for an introduction to box plots)."

also, i added a plot and a paragraph in section 5.3 (on histograms) to say that density plots are smoothed out histograms, and in this text we won't see the technical details for how to compute density plots.
