### ISSUE TITLE
oiRedirect needs to be implemented

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [OpenIntroStat/ims#25]
https://github.com/OpenIntroStat/randomization-and-simulation/blob/f654e833f087aaae38357d163bcbe38236a76899/02-eda.Rmd#L218

In other OpenIntro books that are PDF first we have a function `\oiRedirect{}` that redirects URLs. This is supposed to help with potentially broken links. Need to reimplement in HTML first version.

**Comment by DavidDiez** [comment]
When you build the new variant of `\oiRedirect{}`, the new link format is:

`https://www.openintro.org/go?id=<tag>&referrer=<book_id_and_source>`

The `<book_id_and_source>` value should be something like `isrs2_html` or `isrs2_pdf`.

The original link style should continue to work, but it adds cost because it does a redirect to the /go page first.

**Comment by mine-cetinkaya-rundel** [comment]
@DavidDiez We'll use `ims0_html` for `book_id_and_source`

**Comment by DavidDiez** [comment]
Sounds good, thanks!

**Comment by mine-cetinkaya-rundel** [comment]
@DavidDiez Doing these separately for PDF and HTML is getting tedious. I'm going to opt for `ims1` instead of `ims1_html` and `ims1_pdf`.
