### ISSUE TITLE
Bivariate outliers

### ISSUE THREAD

**Issue by paulvonhippel** [OpenIntroStat/ims#301]
Section 7.3 on outliers in regression should distinguish between univariate and bivariate outliers -- e.g., in Figure 7.3B the circled point is a univariate outlier on both X and Y, but not a bivariate outlier because it is right on the regression line.

**Comment by hardin47** [comment]
figure 7.17, add histograms under the plot for histograms to say univariate outlier yes or no

**Comment by hardin47** [comment]
i did not end up adding histograms because it would have made the plots too busy (can't just add below because the important information is in both the x and y directions)

i did, however, add some discussion about being outliers in the x direction and/or the y direction, as well as discussion on bivariate outliers as discrepant from the linear model.  thanks for the suggestion!
