### ISSUE TITLE
Context of tire tread example in Section 6.2.1

### ISSUE THREAD

**Issue by staceyhancock** [OpenIntroStat/ims#57]
Hi @mine-cetinkaya-rundel and @hardin47,

In reading the tire tread example in Section 6.2.1, I can't figure out if the measurement is the amount of tread left on the tire after 1,000 miles (in which case, higher numbers are better), or the amount of tread worn after 1,000 miles (in which case, lower numbers are better). Based on the manufacturer claims, it seems we're measuring the tread left on the tire, but based on variable descriptions in the plots, it seems we're measuring the tread lost. Is it supposed to be tread left? or tread lost?

Thanks!

**Comment by hardin47** [comment]
I think you mean Section 7.3.1??  I clearly made up this example from nothing, but I tried to find realistic examples.  the example is *trying* to say how much tread is left (the google said things like a good amount of tread was 4/32 of an inch which is about 0.3175 cm).    i just looked through the example, and i think most places it does say tread left.  what image do you see that has a variable description of tread lost?

**Comment by staceyhancock** [comment]
Yes, sorry - Section 7.3.1 (which is our Section 6.3.1). I must have been looking at an earlier version, where the brands were still A and B. I don't see any labels in the figures now that suggest the variable is tread left.  (Previously, the figure with the original data, currently Fig 7.21, had a main title "wear of tire tread (in inches) after 1,000 miles." My only comment now would be that none of the y-axes in the paired boxplot figures have a label. I also don't see the units of measurement (is it cm or in?) listed in the example. I'll double-check that I've pulled before posting another issue! Thanks!

**Comment by hardin47** [comment]
Thanks for bringing this up.  I just added units to all the plot legends (and a few places within the narrative).  I'm not sure that I want to add labels back to those empty plots (which are what I think you are describing).  Leaving the axes off was intentional, as I wanted to reader to really focus on the pairing aspect of the problem, and less on the measurement aspect. I'll leave this GitHub issue open for now, and when Mine and I read through the entire text over the winter holidays, we can talk about what we want to do with this section.

**Comment by mine-cetinkaya-rundel** [comment]
I think we have addressed this as best of we can for now.
